# Generated by Django 5.1.7 on 2025-05-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
