# Generated by Django 5.1.7 on 2025-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_number', models.IntegerField(blank=True, null=True)),
                ('semester_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv_name', models.CharField(max_length=50)),
                ('inv_dept', models.CharField(max_length=50)),
                ('lect_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('number_of_booklets', models.CharField(max_length=50)),
                ('additional_notes', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
