# Generated by Django 5.1.7 on 2025-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordsubmission',
            name='semester_name',
        ),
    ]
