# Generated by Django 5.1.7 on 2025-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_recordsubmission_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsubmission',
            name='number_of_booklets',
            field=models.IntegerField(),
        ),
    ]
