# Generated by Django 5.1.7 on 2025-04-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recordsubmission_number_of_booklets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsubmission',
            name='number_of_booklets',
            field=models.CharField(max_length=50),
        ),
    ]
