# Generated by Django 5.1.7 on 2025-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recordsubmission_number_of_booklets'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsubmission',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
