# Generated by Django 5.1.7 on 2025-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recordsubmission_is_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lect_name', models.CharField(max_length=50)),
                ('number_of_booklets', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('expect_return', models.DateField()),
                ('additional_notes', models.CharField(max_length=350)),
                ('is_collected', models.BooleanField(default=True)),
            ],
        ),
    ]
