# Generated by Django 5.1.7 on 2025-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_recordcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcollection',
            name='course',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordcollection',
            name='department',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
