# Generated by Django 5.1.7 on 2025-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recordcollection_course_recordcollection_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcollection',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
