# Generated by Django 5.1.7 on 2025-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_recordcollection_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcollection',
            name='is_collected',
            field=models.BooleanField(default=True),
        ),
    ]
