# Generated by Django 5.1.7 on 2025-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_recordcollection_is_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lect_name', models.CharField(max_length=50)),
                ('number_of_booklets', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('return_by', models.CharField(max_length=50)),
                ('return_date', models.DateField()),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='fair', max_length=10)),
                ('additional_notes', models.CharField(max_length=350)),
                ('is_returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='recordcollection',
            old_name='is_collected',
            new_name='is_returned',
        ),
    ]
