# Generated by Django 5.1.7 on 2025-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recordreturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsubmission',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'QUIZ'), ('test-1', 'Test-1'), ('test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
    ]
