# Generated by Django 5.1.7 on 2025-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_recordsubmission_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcollection',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'QUIZ'), ('test-1', 'Test-1'), ('test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
        migrations.AddField(
            model_name='recordreturn',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'QUIZ'), ('test-1', 'Test-1'), ('test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
    ]
