# Generated by Django 5.1.7 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_recordcollection_exam_type_recordreturn_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcollection',
            name='exam_type',
            field=models.CharField(choices=[('Quiz', 'QUIZ'), ('Test-1', 'Test-1'), ('Test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
        migrations.AlterField(
            model_name='recordreturn',
            name='exam_type',
            field=models.CharField(choices=[('Quiz', 'QUIZ'), ('Test-1', 'Test-1'), ('Test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
        migrations.AlterField(
            model_name='recordsubmission',
            name='exam_type',
            field=models.CharField(choices=[('Quiz', 'QUIZ'), ('Test-1', 'Test-1'), ('Test-2', 'Test-2'), ('UE', 'UE')], default='UE', max_length=50),
        ),
    ]
